#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
set -x

cd $OPENSHIFT_REPO_DIR/diy/servicemix

bin/servicemix
